/**
 * =================================================
 * =================================================
 * !! DO NOT MODIFY THIS FILE. IT'S AUTOGENERATED !!
 * @TODO: Write script than generates this file
 *        and installs, updates and removes apps
 * =================================================
 * =================================================
 *
 * Installing apps
 * ===============
 *
 * It's the App Hub's job to install apps. The hub can use scripts,
 * provided by the shell, to install, uninstall or update apps.
 * The process is repeatable and deterministic, the source of truth is the app
 * hub. Running the script with the same apps will install/uninstall the same
 * apps and wouldn't have any effect when called multiple times sequentially.
 *
 *
 * What this file would look like
 * ==============================
 *
 * In the future, when we want to replace apps within the shell, instead of
 * with the shell (when the user navigates to another app), the package.json
 * of the shell can contain modules with a path to the installed apps:
 *
 * ```json
 * {
 *   "dependencies": {
 *     "@dhis2/maintenance-app": "../apps/maintenance-app",
 *   }
 * }
 * ```
 *
 * resulting in the following `apps` object:
 *
 * ```js
 * const apps = {
 *   ['@dhis2/maintenance-app']: React.lazy(() =>
 *     import('@dhis2-apps/maintenance')
 *   )
 * }
 * ```
 */

const apps = {}
export default apps
